apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyui-app
  template:
    metadata:
      labels:
        app: pyui-app
    spec:
      containers:
       - name: pyui-app
         image: thanabodin/pyui-app-test:v0.0.6
         ports:
         - containerPort: 3000
         envFrom:
          - secretRef:
              name: pyui-secrets