apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.10
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
          # Load environment variables from the secret 'mongodb-secrets'
          # Expected secrets:
          # - MONGO_INITDB_ROOT_USERNAME: the MongoDB root username
          # - MONGO_INITDB_ROOT_PASSWORD: the MongoDB root password
          envFrom:
            - secretRef:
                name: mongodb-secrets
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
