apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyui-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyui-api
  template:
    metadata:
      labels:
        app: pyui-api
    spec:
      containers:
      - name: pyui-api
        image: thanabodin/pyui-api-test:v0.0.3
        ports:
        - containerPort: 80
        envFrom:
            - secretRef:
                name: pyui-api-secrets

